Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/AccessModifierDeclarations:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
